branches:
  only:
    - pre-prod
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run test
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $github_token
#   local_dir: build
#   on:
#     branch: sensei

# after_script:
# - gulp deploy --host $FTP_HOST --user $FTP_USER --password $FTP_PASSWORD

after_success:
# - printenv
# - echo "${FTP_HOST} $FTP_USER $FTP_PASSWORD"
- find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl -vv --ftp-create-dirs --connection-timeout 3.5 -T {} ftp://ftp.sc3bath3698.universe.wf --user sc3bath3698@sendwebpage.webqbe.com:A1jFbMC0GmXeBGVW4mQtEVb5vzYCZpiU \;